Document: netatalk
Title: Debian netatalk Manual
Author: <insert document author here>
Abstract: This manual describes what netatalk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/netatalk/netatalk.sgml.gz

Format: postscript
Files: /usr/share/doc/netatalk/netatalk.ps.gz

Format: text
Files: /usr/share/doc/netatalk/netatalk.text.gz

Format: HTML
Index: /usr/share/doc/netatalk/html/index.html
Files: /usr/share/doc/netatalk/html/*.html
